spring:
  application:
    name: leadflow-crm

  datasource:
    url: jdbc:mysql://localhost:3306/leadflow_crm
    username: root
    password: YOUR_MYSQL_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080